version: "3.9"

services:
  db:
    image: postgres:15
    container_name: creole-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: creole-backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:4000"
    command: npm run start:prod

  frontend:
    build: ./frontend
    container_name: creole-frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm start

  nlp:
    build: ./nlp
    container_name: creole-nlp
    env_file: .env
    ports:
      - "${NLP_PORT}:8000"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: creole-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import

  minio:
    image: minio/minio:latest
    container_name: creole-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  minio_data: